export const REGIONS = [
  { value: 'toshkent-viloyati', label: "Toshkent viloyati" },
  { value: 'toshkent-shahri', label: "Toshkent shahri" },
  { value: 'andijon', label: "Andijon" },
  { value: 'buxoro', label: "Buxoro" },
  { value: 'fargona', label: "Farg'ona" },
  { value: 'jizzax', label: "Jizzax" },
  { value: 'xorazm', label: "Xorazm" },
  { value: 'namangan', label: "Namangan" },
  { value: 'navoiy', label: "Navoiy" },
  { value: 'qashqadaryo', label: "Qashqadaryo" },
  { value: 'qoraqalpogiston', label: "Qoraqalpog'iston" },
  { value: 'samarqand', label: "Samarqand" },
  { value: 'sirdaryo', label: "Sirdaryo" },
  { value: 'surxondaryo', label: "Surxondaryo" },
] as const;
